CREATE USER 'APPUSER'@'10.10.1.0/24' IDENTIFIED WITH mysql_native_password BY 'USRMYQLP';
select user,host from mysql.user;
create database DATABASENAME;
GRANT ALL PRIVILEGES ON DATABASENAME.* TO 'APPUSER'@'10.10.1.0/24';
FLUSH PRIVILEGES;
